[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview.environment]
  PUBLIC_SITE_URL = "${DEPLOY_PRIME_URL}"
  PUBLIC_BASE_PATH = ""

[context.branch-deploy.environment]
  PUBLIC_SITE_URL = "${DEPLOY_PRIME_URL}"
  PUBLIC_BASE_PATH = ""

[context.production.environment]
  PUBLIC_SITE_URL = "${URL}"
  PUBLIC_BASE_PATH = ""
